import {W,H,DIRS,fresh,localDecision,candidates,step} from './engine.mjs';
const $=id=>document.getElementById(id),canvas=$('board'),ctx=canvas.getContext('2d');
let state=fresh(),paused=false,mode='local',speed=1,round=1,shield=0,direction='DOWN',queued=null,epoch=0,busy=false,last=0,elapsed=0,lastFrame=performance.now(),decisions=0,ms=0,best=0,available=false,jevResult=null,jevPending=false,jevLast=0,jevCount=0,jevFailed=false,execution='smooth';
try{best=Number(localStorage.getItem('jev-snake-best'))||0;}catch{}
for(const d of Object.keys(DIRS))$('directions').insertAdjacentHTML('beforeend',`<div class="direction" id="row-${d}"><span>　${d}</span><span class="bar"><i id="bar-${d}"></i></span><span class="prob" id="prob-${d}">—</span></div>`);
function draw(){const cw=canvas.width/W,ch=canvas.height/H;ctx.fillStyle='#061116';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#1b3a43';for(let y=0;y<H;y++)for(let x=0;x<W;x++){ctx.beginPath();ctx.arc((x+.5)*cw,(y+.5)*ch,1.4,0,Math.PI*2);ctx.fill();}state.snake.forEach((p,i)=>{ctx.fillStyle=i===0?'#e0fff6':`rgb(${Math.round(22+65*(1-i/state.snake.length))},${Math.round(76+136*(1-i/state.snake.length))},${Math.round(67+101*(1-i/state.snake.length))})`;ctx.fillRect(p[0]*cw,p[1]*ch,cw+.2,ch+.2);});if(state.food){ctx.fillStyle='#ffd16f';ctx.beginPath();ctx.arc((state.food[0]+.5)*cw,(state.food[1]+.5)*ch,8,0,Math.PI*2);ctx.fill();}if(state.over){ctx.fillStyle='#031015dc';ctx.fillRect(0,canvas.height/2-46,canvas.width,92);ctx.fillStyle='#e0fff6';ctx.font='28px monospace';ctx.textAlign='center';ctx.fillText(state.won?'BOARD COMPLETE':'GAME OVER · R TO RESET',canvas.width/2,canvas.height/2+10);}}
const glyphs=['111101101101111','010110010010111','111001111100111','111001111001111','101101111001001','111100111001111','111100111101111','111001001001001','111101111101111','111101111001111'];
function pixelNumber(id,value){let rects='';String(value).padStart(3,'0').split('').forEach((d,i)=>{[...glyphs[+d]].forEach((v,j)=>{if(v==='1')rects+=`<rect x="${i*4+j%3}" y="${Math.floor(j/3)}" width="1" height="1"/>`;});});$(id).innerHTML=`<svg viewBox="0 0 11 5" role="img" aria-label="${value}" fill="currentColor">${rects}</svg>`;}
function render(){for(const [id,v] of Object.entries({score:String(state.score).padStart(3,'0'),length:String(state.snake.length).padStart(3,'0'),best:String(best).padStart(3,'0'),shield:String(shield).padStart(4,'0'),percent:(state.snake.length/(W*H)*100).toFixed(1)+'%',clock:`${String(Math.floor(elapsed/60000)).padStart(2,'0')}:${String(Math.floor(elapsed/1000)%60).padStart(2,'0')}`,round:'ROUND '+String(round).padStart(2,'0')}))$(id).textContent=v;pixelNumber('score',state.score);pixelNumber('length',state.snake.length);pixelNumber('best',best);$('fill').style.width=state.snake.length/(W*H)*100+'%';$('pause').textContent=paused?'继续':'暂停';$('run').textContent=(state.over?'FINISHED':paused?'PAUSED':'LIVE RUN')+' · '+speed+'×';draw();}
function stats(result){for(const d of Object.keys(DIRS)){$('row-'+d).classList.toggle('active',result.choice===d);$('bar-'+d).style.width=(result.probabilities[d]??0)*100+'%';$('prob-'+d).textContent=(result.probabilities[d]??0).toFixed(2);}$('executing').textContent=direction+(result.choice!==direction?' *':'');$('latency').textContent=ms.toFixed(1)+' ms';$('rate').textContent=(decisions/Math.max(elapsed/1000,.001)).toFixed(1)+' /s';const risk=candidates(state).filter(c=>!c.legal).length/4,free=1-state.snake.length/(W*H);$('risk').textContent=risk.toFixed(2);$('riskbar').style.width=risk*100+'%';$('free').textContent=free.toFixed(2);$('freebar').style.width=free*100+'%';}
async function askJev(){
 if(jevFailed||jevPending||paused||state.over||mode!=='jev'||performance.now()-jevLast<250)return;
 jevPending=true; const version=epoch;
 try{const cs=candidates(state);const response=await fetch('/api/decision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({head:state.snake[0],food:state.food,candidates:cs.map(({direction,safe,legal,distance,advance,eat})=>({direction,safe,legal,distance,advance,eat}))}),signal:AbortSignal.timeout(10000)});const result=await response.json();if(!response.ok)throw Error(result.error||'Jev 请求失败');if(version!==epoch)return;jevCount++;jevResult=result;ms=result.ms;if(execution==='strict')tick(true);stats(result);$('latency').textContent=ms.toFixed(1)+' ms';$('rate').textContent=jevCount/Math.max(elapsed/1000,.001)>0?(jevCount/Math.max(elapsed/1000,.001)).toFixed(1)+' /s':'—';
 }catch(e){if(version===epoch){jevFailed=true;$('network').textContent='DISCONNECTED';$('notice').textContent=e.message+' 流畅模式由本地算法继续，点击「重连 Jev」恢复请求。';render();}}
 finally{jevPending=false;jevLast=performance.now();}
}
function tick(fromJev=false){if(paused||state.over||(mode==='jev'&&execution==='strict'&&!fromJev))return;let result=localDecision(state);const start=performance.now();if(mode==='manual'){direction=queued??direction;queued=null;}else if(mode==='jev'){
 const proposed=jevFailed?null:jevResult?.choice, candidate=candidates(state).find(c=>c.direction===proposed);
 if(candidate?.safe)direction=proposed;else {direction=result.choice;if(proposed)shield++;}
 // Latest Jev preference is advisory; validate it against the current board on every frame.
 }else direction=result.choice;
 step(state,direction);decisions++;
 if(state.score>best){best=state.score;try{localStorage.setItem('jev-snake-best',String(best));}catch{}}
 if(mode!=='jev'){ms=performance.now()-start;stats(result);}else if(jevResult){stats(jevResult);$('rate').textContent=(jevCount/Math.max(elapsed/1000,.001)).toFixed(1)+' /s';}
 render();last=performance.now();}
function reset(){epoch++;jevResult=null;jevCount=0;jevFailed=false;state=fresh();round++;elapsed=0;decisions=0;shield=0;paused=false;direction='DOWN';queued=null;render();}
function pause(){paused=!paused;epoch++;render();}
function setSpeed(v){speed=Math.max(.25,Math.min(8,v));render();}
function turn(d){if(mode!=='manual'||queued)return;const a=DIRS[d],b=DIRS[direction];if(a[0]!==-b[0]||a[1]!==-b[1])queued=d;}
$('execution').onchange=()=>{execution=$('execution').value;epoch++;jevResult=null;$('notice').textContent=execution==='strict'?'逐步模式：每走一格都等待一次新的 Jev 推理。':'流畅模式：20 格/秒，本地安全执行与后台 Jev 决策独立运行。';};$('retry').onclick=()=>{jevFailed=false;jevLast=0;$('network').textContent='ONLINE';$('notice').textContent='正在恢复 Jev 后台决策。';};$('pause').onclick=pause;$('reset').onclick=reset;$('slower').onclick=()=>setSpeed(speed/2);$('faster').onclick=()=>setSpeed(speed*2);document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>turn(b.dataset.dir));
$('mode').onchange=()=>{if($('mode').value==='jev'&&!available){$('notice').textContent='尚未配置服务端 TYPESAFE_API_KEY。';$('mode').value=mode;return;}mode=$('mode').value;reset();const jev=mode==='jev',manual=mode==='manual';$('engine').textContent=jev?'Jev / TypeSafe':manual?'MANUAL / PLAYER':'LOCAL / CYCLE';$('subtitle').textContent=jev?'异步方向决策 + 本地安全执行':manual?'方向键 / WASD 控制':'本地算法 · 即时演示';$('distribution').textContent=jev?'LATEST JEV PROBABILITIES':'HEURISTIC WEIGHTS';$('network').textContent=jev?'ONLINE':'OFFLINE';$('model').textContent=jev?'jev-1.13.0':manual?'Human':'Hamiltonian cycle';$('latencylabel').textContent=jev?'API ROUND TRIP':'COMPUTE';$('notice').textContent=jev?'流畅模式：蛇以 20 格/秒运行；Jev 后台更新方向偏好，本地安全算法逐步执行。右侧为最近一次模型概率。':manual?'方向键 / WASD 移动；空格暂停，R 重开。右侧为算法参考。':'本地算法演示中；右侧显示启发式权重，不代表 Jev 模型概率。';};
window.addEventListener('keydown',e=>{if(e.target.matches('select,button,input'))return;const k=e.key.toLowerCase(),dirs={arrowup:'UP',w:'UP',arrowdown:'DOWN',s:'DOWN',arrowleft:'LEFT',a:'LEFT',arrowright:'RIGHT',d:'RIGHT'};if(k===' '||k.startsWith('arrow'))e.preventDefault();if(k===' ')pause();else if(k==='r')reset();else if(mode==='manual'&&dirs[k])turn(dirs[k]);else if(k==='arrowup')setSpeed(speed*2);else if(k==='arrowdown')setSpeed(speed/2);});
function frame(now){const delta=now-lastFrame;lastFrame=now;if(!paused&&!state.over)elapsed+=delta;if(mode==='jev')askJev();if(now-last>50/(speed*(mode==='manual'?.3:1)))tick();$('clock').textContent=`${String(Math.floor(elapsed/60000)).padStart(2,'0')}:${String(Math.floor(elapsed/1000)%60).padStart(2,'0')}`;requestAnimationFrame(frame);}render();requestAnimationFrame(frame);
fetch('/api/status').then(r=>r.json()).then(s=>{available=s.available;if(available){$('mode').value='jev';$('mode').onchange();}}).catch(()=>{});
