import {W,H,DIRS,fresh,localDecision,candidates,step} from './engine.mjs';
const $=id=>document.getElementById(id),names=['laya','jev'];
let running=false,runId=0,started=0,finished=0,kind='',records=[],metadata={},ready=false,activeTask=null;
function rng(seed){let n=seed>>>0;return()=>((n=(Math.imul(n,1664525)+1013904223)>>>0)/4294967296);}
const players={};
for(const id of names){const isLaya=id==='laya';$('panels').insertAdjacentHTML('beforeend',`<article class="panel ${id}"><div class="panelhead"><div><h2>${isLaya?'LAYA':'JEV'}</h2><p>${isLaya?'convaiinnovations/laya · 421M':'TypeSafe · jev-1.13.0'}</p></div><span class="tag">${isLaya?'LOCAL / MLX':'REMOTE / API'}</span></div><div class="inner"><div class="topstats"><div><strong id="${id}-score">000</strong><span> SCORE</span> &nbsp; <span id="${id}-length">LENGTH 006</span></div><div class="state" id="${id}-state">等待开始</div></div><canvas id="${id}-board" width="960" height="582" aria-label="${id} 贪吃蛇棋盘"></canvas><div class="numbers"><div><small>${isLaya?'PREDICT':'API ROUND TRIP'}</small><strong id="${id}-latest">—</strong></div><div><small>P50 LATENCY</small><strong id="${id}-p50">—</strong></div><div><small>DECISIONS / S</small><strong id="${id}-rate">—</strong></div><div><small>DECISIONS</small><strong id="${id}-count">0</strong></div></div><div class="lower"><div>${names.length&&Object.keys(DIRS).map(d=>`<div class="row" id="${id}-${d}"><span>${d}</span><span class="bar"><i></i></span><span class="prob">—</span></div>`).join('')}</div><dl><dt>P95 / ms</dt><dd id="${id}-p95">—</dd><dt>浏览器 E2E P50</dt><dd id="${id}-e2e">—</dd><dt>执行方向</dt><dd id="${id}-move">—</dd><dt>安全修正</dt><dd id="${id}-shield">0</dd></dl></div><div class="error" id="${id}-error"></div></div></article>`);players[id]={state:fresh(),samples:[],e2e:[],shield:0,result:null,executed:null,random:rng(2026),error:'',end:0};}
const quantile=(xs,q)=>{if(!xs.length)return null;const a=[...xs].sort((a,b)=>a-b);return a[Math.max(0,Math.ceil(a.length*q)-1)];};
const fmt=n=>n===null||!Number.isFinite(n)?'—':n.toFixed(1);
function draw(id){const p=players[id],s=p.state,c=$(id+'-board'),ctx=c.getContext('2d'),cw=c.width/W,ch=c.height/H;ctx.fillStyle='#071219';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#1d3744';for(let y=0;y<H;y++)for(let x=0;x<W;x++)ctx.fillRect((x+.5)*cw,(y+.5)*ch,2,2);for(let i=s.snake.length-1;i>=0;i--){const [x,y]=s.snake[i];ctx.fillStyle=i===0?'#e8fff7':id==='laya'?`rgba(73,221,176,${.24+.7*(1-i/s.snake.length)})`:`rgba(132,175,255,${.24+.7*(1-i/s.snake.length)})`;ctx.fillRect(x*cw,y*ch,cw+.3,ch+.3);}if(s.food){ctx.beginPath();ctx.arc((s.food[0]+.5)*cw,(s.food[1]+.5)*ch,8,0,Math.PI*2);ctx.fillStyle='#ffcf70';ctx.fill();}}
function render(){for(const id of names){const p=players[id],s=p.state;$(`${id}-score`).textContent=String(s.score).padStart(3,'0');$(`${id}-length`).textContent='LENGTH '+String(s.snake.length).padStart(3,'0');$(`${id}-latest`).innerHTML=fmt(p.samples.at(-1)??null)+'<i> ms</i>';$(`${id}-p50`).innerHTML=fmt(quantile(p.samples,.5))+'<i> ms</i>';$(`${id}-p95`).textContent=fmt(quantile(p.samples,.95));$(`${id}-e2e`).textContent=fmt(quantile(p.e2e,.5))+' ms';$(`${id}-count`).textContent=p.samples.length;const seconds=((p.end||finished||performance.now())-started)/1000;$(`${id}-rate`).textContent=kind==='race'&&started&&seconds>0?(p.samples.length/seconds).toFixed(1):'—';$(`${id}-move`).textContent=(p.executed??'—')+(p.result&&p.executed!==p.result.choice?' *':'');$(`${id}-shield`).textContent=p.shield;$(`${id}-error`).textContent=p.error;if(p.result)for(const d of Object.keys(DIRS)){const el=$(`${id}-${d}`);el.classList.toggle('active',p.result.choice===d);el.querySelector('i').style.width=(p.result.probabilities[d]??0)*100+'%';el.querySelector('.prob').textContent=(p.result.probabilities[d]??0).toFixed(2);}draw(id);}const ms=started?Math.max(0,(finished||performance.now())-started):0;$('elapsed').textContent=String(Math.floor(ms/60000)).padStart(2,'0')+':'+(ms/1000%60).toFixed(1).padStart(4,'0');}
function payload(s){return {candidates:candidates(s).map(({direction,safe,legal,distance,advance,eat})=>({direction,safe,legal,distance,advance,eat}))};}
async function request(id,body){const start=performance.now();const response=await fetch(id==='laya'?'http://127.0.0.1:8878/api/decision':'/api/decision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(12000)});const r=await response.json();if(!response.ok)throw Error(r.error||`HTTP ${response.status}`);if(!Number.isFinite(r.ms)||!Object.hasOwn(DIRS,r.choice)||Object.keys(DIRS).some(d=>!Number.isFinite(r.probabilities?.[d])))throw Error('无效模型响应');return {...r,e2e_ms:performance.now()-start};}
function apply(id,result,s,advance=true){const p=players[id],safe=candidates(s).filter(c=>c.safe).sort((a,b)=>result.probabilities[b.direction]-result.probabilities[a.direction]);if(!safe.length)throw Error('安全环路没有可执行方向');p.executed=safe[0].direction;if(p.executed!==result.choice)p.shield++;p.result=result;p.samples.push(result.ms);p.e2e.push(result.e2e_ms);if(advance)step(p.state,p.executed,p.random);}
function reset(){records=[];finished=0;started=0;for(const id of names)Object.assign(players[id],{state:fresh(),samples:[],e2e:[],shield:0,result:null,executed:null,random:rng(Number($('seed').value)||2026),error:'',end:0});render();}
function controls(on){$('start').disabled=on||!ready;$('paired').disabled=on||!ready;$('pause').disabled=!on;$('seed').disabled=on;$('export').disabled=on||!records.length;}
async function warmup(){const input=payload(fresh());$('status').textContent='预热两种模型（不计入统计）';const results=await Promise.allSettled(names.map(id=>request(id,input)));results.forEach((r,i)=>{if(r.status==='rejected')players[names[i]].error=r.reason.message;});if(results.some(r=>r.status==='rejected'))throw Error('预热失败，请重试');}
async function raceOne(id,version){const p=players[id];$(`${id}-state`).textContent='逐步推理 / MAX SPEED';while(running&&runId===version&&!p.state.over&&performance.now()-started<30000){const input=payload(p.state);try{const r=await request(id,input);if(!running||runId!==version)break;apply(id,r,p.state);records.push({engine:id,step:p.samples.length,input,result:r,executed:p.executed,score:p.state.score});}catch(e){p.error=e.message;break;}}p.end=performance.now();$(`${id}-state`).textContent=p.error?'请求失败 / 已停止':p.state.won?'棋盘填满':p.state.over?'GAME OVER':'已停止';}
async function startRace(){if(activeTask)return;reset();kind='race';running=true;const version=++runId;controls(true);activeTask=(async()=>{try{await warmup();if(!running)return;started=performance.now();$('status').textContent='双机竞速 · 30 秒 · 每步真实推理';await Promise.all(names.map(id=>raceOne(id,version)));}catch(e){$('status').textContent=e.message;}finally{finished=performance.now();running=false;activeTask=null;controls(false);if(started)$('status').textContent='竞速结束 · 可导出记录';render();}})();}
function fixtures(){const s=fresh(),random=rng(Number($('seed').value)||2026),out=[];for(let i=0;i<20;i++){for(let j=0;j<11;j++)step(s,localDecision(s).choice,random);out.push(structuredClone(s));}return out;}
async function paired(){if(activeTask)return;reset();kind='paired';running=true;const version=++runId;controls(true);$('result').textContent='相同输入逐轮测量中…';activeTask=(async()=>{try{await warmup();if(!running)return;started=performance.now();for(const [index,s] of fixtures().entries()){if(!running||runId!==version)break;const input=payload(s);for(const id of names){players[id].state=structuredClone(s);$(`${id}-state`).textContent=`同题输入 ${index+1} / 20`;}const results=await Promise.allSettled(names.map(id=>request(id,input)));if(!running||runId!==version)break;const row={sample:index+1,input,board:s,results:{}};for(let i=0;i<names.length;i++){const id=names[i],r=results[i];if(r.status==='fulfilled'){apply(id,r.value,s,false);row.results[id]=r.value;}else{players[id].error=r.reason.message;row.results[id]={error:r.reason.message};}}records.push(row);$('status').textContent=`同题测速 ${index+1}/20`;if(results.some(r=>r.status==='rejected'))break;}
const valid=records.filter(r=>r.results?.laya?.ms&&r.results?.jev?.ms);const l=quantile(valid.map(r=>r.results.laya.ms),.5),j=quantile(valid.map(r=>r.results.jev.ms),.5);$('ratio').innerHTML=(l&&j?(j/l).toFixed(1)+'×':'—')+'<small>JEV / LAYA · P50</small>';$('result').textContent=`同题实测：Laya ${fmt(l)} ms · Jev ${fmt(j)} ms`;$('detail').textContent=`${valid.length}/20 组成对有效样本；预热不计入统计，无结果缓存。Jev 包含网络往返，Laya 为本机预测耗时。`;
}catch(e){$('status').textContent=e.message;}finally{finished=performance.now();running=false;activeTask=null;controls(false);if(started)$('status').textContent='同题测速结束';render();}})();}
$('start').onclick=startRace;$('paired').onclick=paired;$('pause').onclick=()=>{running=false;runId++;$('status').textContent='正在等待在途请求结束';$('pause').disabled=true;};
$('export').onclick=()=>{const report={date:new Date().toISOString(),mode:kind,seed:Number($('seed').value),metadata,measurement:'Laya local predict wall time vs Jev remote API wall time including network. Warmups excluded. One uncached choice per move. Browser E2E separately recorded.',records};const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='laya-jev-'+kind+'-'+Date.now()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
async function check(){try{const [l,j]=await Promise.all([fetch('http://127.0.0.1:8878/api/status').then(r=>r.json()),fetch('/api/status').then(r=>r.json())]);metadata={laya:l,jev:j};$('hardware').textContent=l.hardware+' · MLX FP16 · Laya English 421M';ready=l.ready&&j.available;$('status').textContent=ready?'模型就绪 · READY':l.error||'Laya 正在加载和预热…';if(!ready&&!l.error)setTimeout(check,2000);controls(false);}catch(e){$('status').textContent='等待本机 Laya 服务…';setTimeout(check,2000);}}
let lastRender=0;function frame(now){if(now-lastRender>80){render();lastRender=now;}requestAnimationFrame(frame);}render();requestAnimationFrame(frame);check();
fetch('/benchmark-paired.json').then(r=>r.ok?r.json():null).then(report=>{if(!report||running||records.length)return;const rows=report.records.filter(r=>r.results?.laya?.ms&&r.results?.jev?.ms);const l=quantile(rows.map(r=>r.results.laya.ms),.5),j=quantile(rows.map(r=>r.results.jev.ms),.5);$('result').textContent=`已保存同题实测：Laya ${fmt(l)} ms · Jev ${fmt(j)} ms`;$('detail').textContent=`${rows.length}/20 组成对样本 · ${new Date(report.date).toLocaleString()} · 本机 MLX 与远程 API 往返。点击同题测速可重新测量。`;$('ratio').innerHTML=(j/l).toFixed(1)+'×<small>JEV / LAYA · P50</small>';}).catch(()=>{});
